### ISSUE TITLE
Latest source hits error if UI test has a failure

### ISSUE THREAD

**Issue by ChrisMash** [xcpretty/xcpretty#391]
A project I work on installed xcpretty from the latest source in CI (not sure why, it doesn't after hitting this issue 😁)

Our tests started hitting the following error when piping the output of xcodebuild (Xcode 15, running UI tests) to xcpretty when one of the tests failed:

```
tools/lib/xcpretty/parser.rb:366:in `parse': uninitialized constant XCPretty::Parser::ERB (NameError)
        formatter.format_failing_test($2, $3, ERB::Util.html_escape($4), $1)
                                                 ^^^^^^
	from /Users/vagrant/.mobile-sdk/tools/lib/xcpretty/formatters/formatter.rb:88:in `pretty_format'
	from /Users/vagrant/.mobile-sdk/tools/lib/xcpretty/printer.rb:19:in `pretty_print'
	from /Users/vagrant/.mobile-sdk/tools/bin/xcpretty:84:in `block in <main>'
	from /Users/vagrant/.mobile-sdk/tools/bin/xcpretty:83:in `each_line'
	from /Users/vagrant/.mobile-sdk/tools/bin/xcpretty:83:in `<main>'
```

It was working fine previously, until the xcpretty source was updated the other day

**Comment by ChrisMash** [comment]
I imagine this is the commit that did it: https://github.com/xcpretty/xcpretty/commit/16a96b7123fdd387a14d25f98c75cadd4d53180f

**Comment by jblaker** [comment]
We just started encountering this issue in our Jenkins UI Testing pipeline. Not sure why we're seeing it all of the sudden if it's been around thing long.

**Comment by juan-arias** [comment]
Same for us, is there a workaround we can use?

**Comment by ChrisMash** [comment]
Pull down the latest release of the prior commit rather than the absolute latest 👌🏻

**Comment by aureliendelrue** [comment]
Any news ?

**Comment by ThomasHezard** [comment]
Same error appeared very recently for me.

Any update from the xcpretty team?

**Comment by tdr-alays** [comment]
Some issue here for couple of weeks, any updates please .

**Comment by revolter** [comment]
Really sorry for introducing this issue 🙈 I tested it with my project, back then, and it worked, somehow 🤷🏻

I created #400 to fix this, but since I'm not able to reproduce the original issue, I can't test the fix either. As such, would one of you folks mind testing it and confirm that it fixes the crash, please? 🙏🏻

**Comment by nickx3389** [comment]
Is there a new release for this? I still get this error.

**Comment by tdr-alays** [comment]
> Is there a new release for this? I still get this error.

@revolter made a fix but he doesn't have access to create a new tag.

Maybe @kattrali can ?

**Comment by revolter** [comment]
I released the fix for this in version `0.4.1` ✅
