### ISSUE TITLE
Getting error with Xcode 16

### ISSUE THREAD

**Issue by SanketSB237** [xcpretty/xcpretty#397]
I am getting this error since we moved to Xcode 16. XCPretty versions not changed. I also tried with latest version but same error is thrown.

> /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `===': invalid byte sequence in US-ASCII (ArgumentError)
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:434:in `update_test_state'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/parser.rb:307:in `parse'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/formatters/formatter.rb:88:in `pretty_format'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/lib/xcpretty/printer.rb:19:in `pretty_print'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:84:in `block in <top (required)>'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:83:in `each_line'
> 	from /Library/Ruby/Gems/2.6.0/gems/xcpretty-0.3.0/bin/xcpretty:83:in `<top (required)>'
> 	from /usr/local/bin/xcpretty:23:in `load'
> 	from /usr/local/bin/xcpretty:23:in `<main>'

**Comment by alexbuisson** [comment]
no news on that issue ? I'm facing the same
using xcpretty v0.3.0
command used : xcodebuild .... | xcpretty 

got exactly the same error message

**Comment by gatjamf** [comment]
I see the same in 0.4.0:

`
✓ testSomething(0.006 seconds)
/Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/parser.rb:366:in `parse': uninitialized constant XCPretty::Parser::ERB (NameError)

formatter.format_failing_test($2, $3, ERB::Util.html_escape($4), $1)
                                              ^^^
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/formatters/formatter.rb:88:in 'pretty_format'
	from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/printer.rb:19:in 'pretty_print'
....
`

**Comment by alexbuisson** [comment]
> I see the same in 0.4.0:
> 
> `✓ testSomething(0.006 seconds) /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/parser.rb:366:in`parse': uninitialized constant XCPretty::Parser::ERB (NameError)
> 
> formatter.format_failing_test($2, $3, ERB::Util.html_escape($4), $1) ^^^ from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/formatters/formatter.rb:88:in 'pretty_format' from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/printer.rb:19:in 'pretty_print' .... `

Hi, I decided to move to xcbeautify, the switch was easy.

**Comment by shahzadmajeed** [comment]
> > I see the same in 0.4.0:
> > `✓ testSomething(0.006 seconds) /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/parser.rb:366:in`parse': uninitialized constant XCPretty::Parser::ERB (NameError)
> > formatter.format_failing_test($2, $3, ERB::Util.html_escape($4), $1) ^^^ from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/formatters/formatter.rb:88:in 'pretty_format' from /Users/anka/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/xcpretty-0.4.0/lib/xcpretty/printer.rb:19:in 'pretty_print' .... `
> 
> Hi, I decided to move to xcbeautify, the switch was easy.

Same, I have moved to xcbeautify temporarily until this issue is fixed.
